$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = test $(hostname) = "amir-pc" || systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 120 
    on-timeout = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
