$text_color = rgba(FFFFFFFF)
$entry_background_color = rgba(33333322)
$entry_border_color = rgba(7AA2F7FF)
$entry_color = rgba(FFFFFFFF)
$font_family = Code New Roman
$font_family_clock = Code New Roman
$font_material_symbols = Material Symbols Rounded

background {
  path = screenshot
  path = ~/Pictures/Wallpapers/north.png
  blur_size = 2
  blur_passes = 3
	# vibrancy = 0.1696
	#  vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}


input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    outer_color = $entry_border_color
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = $text_color
    fade_on_empty = false
    rounding = 15
    placeholder_text = Enter Password
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    position = 0, 20
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = $text_color
    font_size = 18
    font_family = SF Pro Display Bold
    position = 0, 85
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, 0.70)
    font_size = 25
    font_family = $font_family_clock
    position = 0, 370
    halign = center
    valign = center
}

label { # Clock
    monitor =
    text = $TIME
    shadow_passes = 1
    shadow_boost = 0.5
    color = $text_color
    font_size = 65
    font_family = $font_family_clock

    position = 0, 300
    halign = center
    valign = center
}


label { # Status
    monitor =
    text = cmd[update:5000] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/status.sh
    shadow_passes = 1
    shadow_boost = 0.5
    color = $text_color
    font_size = 14
    font_family = $font_family

    position = 0, 35
    halign = center
    valign = bottom
}
