require("config.autocmds")
require("config.options")
require("config.lsp")
require("plugins")
require("config.keymaps")
vim.cmd.colorscheme("eldritch")
local highlights = require("config.highlights")
highlights.apply()
