-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.cmd([[
--   :hi NeoTreeNormal guibg=#11121D
--   :hi NeoTreeNormalNC guibg=#11121D
--   :hi NeoTreeEndOfBuffer guibg=#11121D
-- ]])
