kitty_mod 		    ctrl+shift
font_family       family="FiraCode Nerd Font Mono" style=Light
bold_font         auto
italic_font       auto
bold_italic_font  auto
disable_ligatures always

text_fg_override_threshold -10

font_size 12
cursor_shape block
copy_on_select yes
allow_remote_control yes
listen_on unix:@mykitty
shell_integration enabled

# Windows
remember_window_size yes
initial_window_width 1024
initial_winfow_height 768
hide_window_decorations yes 
window_border_width 0.5pt

# Tabs
tab_bar_edge top
tab_bar_style custom
tab_separator ""
tab_bar_min_tabs 1
tab_title_max_length 20
tab_bar_margin_height   0 0
tab_bar_margin_width    0
tab_title_template " {fmt.noitalic}{fmt.fg.tab}{index}{'' if layout_name == 'stack' else ''} {title}{tab.active_oldest_exe}{activity_symbol} {tab.progress_percent}{bell_symbol} "
active_tab_title_template " {fmt.noitalic}{fmt.fg.tab}{index}{'' if layout_name == 'stack' else ''} {title}{tab.active_oldest_exe}{activity_symbol} {tab.progress_percent}{bell_symbol} "

# Debugging
forward_stdio yes

# New window
map alt+enter new_window

# Mouse
mouse_map left click ungrabbed no_op
mouse_map cmd+left click ungrabbed mouse_handle_click selection link

# Move between windows
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l map alt+k neighboring_window up

# Search scrollback
map alt+f search_scrollback

# Last command
map alt+g show_last_command_output
map alt+c copy_last_command_output

# Make shift+insert behave like ctrl+v
map shift+insert paste_from_clipboard

# Toggle fullscreen
map alt+z toggle_layout stack
map alt+n next_layout
map alt+shift+n next_layout -1

# Command palette
map alt+o command_palette

# Prompt
map --allow-fallback=shifted,ascii alt+up scroll_to_prompt -1
map --allow-fallback=shifted,ascii alt+down scroll_to_prompt 1

# Tabs
map alt+t new_tab
map alt+h previous_tab
map alt+l next_tab
map alt+. move_tab_forward
map alt+, move_tab_backward

# Scrolling
map page_up scroll_page_up
map page_down scroll_page_down

# Reset font size
map ctrl+0 change_font_size all 0
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

# Go to previously active tab
map alt+a goto_tab -1

map ctrl+å send_text all \x1e

# Set bell icon
# bell_on_tab ⚠
enable_audio_bell no

# Theming
tab_bar_background #16161e
background #0b0d11
foreground #bdbdbd

# BEGIN_KITTY_THEME
# Eldritch
include current-theme.conf
# END_KITTY_THEME
