[shell.panel]
transparency_mode = "glass"
control_center_placement = "floating"
session_placement = "floating"
open_near_click_control_center = true
open_near_click_session = true
floating_layer = "top"
floating_offset = 0


[osd]
background_opacity = 0.6 # background opacity of OSD popups
offset_y = 36

[theme]
mode              = "dark"        # dark | light | auto
source            = "community"     # builtin | wallpaper | community | custom
builtin           = "Breeze"    # bundled palette name
pure_black_dark = true

[bar]

[bar.default]
font_family = "NotoSans Nerd Font"
capsule = true
capsule_fill = "surface"
capsule_opacity = 0.5
capsule_radius = 10.0
capsule_padding = 8
shadow = false
background_opacity = 0
margin_ends = -8
radius = 0
thickness = 38

start  = ["workspaces", "active_window"]
center = ["privacy", "media"]
end    = ["tray", "notifications", "clipboard", "bluetooth", "network",  "volume", "battery", "clock", "session"]

[dock]
enabled = false

[widget.privacy]
hide_inactive = true

[widget.clock]
format = "{:%a %e %b %H:%M}"

[widget.workspaces]
display = "none"
focused_color = "#80a0ff"
occupied_color = "#808080"
empty_color = "#505050"
active_pill_size = 1.6

[control_center]
sidebar = "none"

[lockscreen]
enabled = false


[notification]
background_opacity       = 0.6 
offset_y = 0

[location]
auto_locate = false
address     = "Varberg, Sweden"    # geocoded when auto_locate = false and non-empty
