BROWSER=zen-browser
TERMINAL=wezterm
ELECTRON_OZONE_PLATFORM_HINT=auto
GDK_BACKEND=wayland
HYPRCURSOR_SIZE=24
HYPRCURSOR_THEME=Bibata-Modern-Ice
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME="qt6ct"
QT_STYLE_OVERRIDE=kvantum
QT_WAYLAND_DISABLE_WINDOWDECORATION="1"
XCURSOR_SIZE=24
XCURSOR_THEME=Bibata-Modern-Ice
