theme = "blur"
ext_background_effect_blur = true
force_keyboard_focus = true

[keybinds]
close = ["Escape", "ctrl c"]
next = ["ctrl n"]
previous = ["ctrl p"]
pin = []

[providers]
default = [
  "desktopapplications",
  "calc",
  "runner",
  "menus",
  "websearch",
	"files",
	"clipboard"
]

[providers.actions]

desktopapplications = [
  { action = "start", default = true, bind = "Return" },
  { action = "start:keep", label = "open+next", bind = "shift Return", after = "KeepOpen" },
  { action = "new_instance", label = "new instance", bind = "ctrl Return" },
  { action = "new_instance:keep", label = "new+next", bind = "ctrl alt Return", after = "KeepOpen" },
  { action = "pin" },
  { action = "unpin" },
  { action = "pinup" },
  { action = "pindown" },
]

