# theme = "blur"
ext_background_effect_blur = true
force_keyboard_focus = true

[keybinds]
close = ["Escape", "ctrl c"]
next = ["ctrl n"]
previous = ["ctrl p"]
down = ["ctrl n"]
up = ["ctrl p"]

[providers]
default = [
  "desktopapplications",
  "calc",
  "runner",
  "menus",
  "websearch",
	"files"
]
